.job_template:
  image: "d2s://external/docker/debian:bookworm"
  tags: ["ace-x86_64"]
  variables:
    SCALENODE_CPU: 2
    SCALENODE_DISK: 10
    SCALENODE_RAM: 2048
    DEBIAN_FRONTEND: noninteractive

stages:
  - build

Build PCIe Communication Server:
  stage: build
  extends: .job_template

  before_script:
    - apt update -qq
    - apt-mark hold tzdata # don't update tzdata, as it sometimes fails to update in CI
    - apt upgrade -y -qq
    - apt install -y -qq cmake python3-dev python3-pip python3-venv git lcov libgtest-dev

  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -e git+https://github.com/antmicro/tuttest#egg=tuttest
    - tuttest README.md server-build | bash -o pipefail -
    
    - ./build/server-tests
    - ./scripts/coverage.sh
    - tar czf coverage.tar.gz coverage

  artifacts:
    paths:
      - build/server
      - build/server-tests
      - coverage.tar.gz
    when: always

Build Zephyr Samples:
  stage: build
  extends: .job_template
  image: "d2s://external/docker/zephyrprojectrtos/ci:v0.26.5"
  variables:
    CMAKE_PREFIX_PATH: /opt/toolchains

  script:
    - pip3 install -e git+https://github.com/antmicro/tuttest#egg=tuttest
    - tuttest zephyr-samples/pcie_scan/README.md pcie-scan-prep | bash -o pipefail -

    # PCIe Scan sample
    - tuttest zephyr-samples/pcie_scan/README.md pcie-scan-build | bash -o pipefail -
    - tar czf pcie_scan.tar.gz build.pcie_scan

    # PCIe NVMe sample
    - tuttest zephyr-samples/pcie_nvme/README.md pcie-nvme-build | bash -o pipefail -
    - tar czf pcie_nvme.tar.gz build.pcie_nvme

    # PCIe IVSHMEM sample
    - tuttest zephyr-samples/pcie_ivshmem/README.md pcie-ivshmem-build | bash -o pipefail -
    - tar czf pcie_ivshmem.tar.gz build.pcie_ivshmem

    # PCIe DMA sample
    - tuttest zephyr-samples/pcie_dma/README.md pcie-dma-build | bash -o pipefail -
    - tar czf pcie_dma.tar.gz build.pcie_dma

    # Run sample
    - tuttest zephyr-samples/pcie_dma/README.md pcie-dma-memory-mock,pcie-dma-net-setup,pcie-dma-run,pcie-dma-teardown | bash -o pipefail -

  artifacts:
    paths:
      - pcie_*.tar.gz
    when: always

Checkpatch:
  stage: build
  extends: .job_template

  before_script:
    - apt update -qq
    - apt-mark hold tzdata # don't update tzdata, as it sometimes fails to update in CI
    - apt upgrade -y -qq
    - apt install -y -qq wget perl

  script:
    # Download checkpatch.pl script directly from the Linux kernel source tree
    - wget https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/scripts/checkpatch.pl
    - chmod +x checkpatch.pl

    # Use xargs instead of find's -exec due to the status return code limitation in find
    - find . -iname '*.[ch]' -not -path "./build/*" -and -not -path "./tests/*" -and -not -path "./zephyr-samples/drivers/dma/*" | xargs ./checkpatch.pl -f --no-tree
