.job_template:
  image: "d2s://external/docker/debian:bookworm"
  tags: ["ace-x86_64"]
  variables:
    SCALENODE_CPU: 2
    SCALENODE_DISK: 10
    SCALENODE_RAM: 2048
    DEBIAN_FRONTEND: noninteractive

stages:
  - build

Build PCIe Communication Server:
  stage: build
  extends: .job_template

  before_script:
    - apt update -qq
    - apt-mark hold tzdata # don't update tzdata, as it sometimes fails to update in CI
    - apt upgrade -y -qq
    - apt install -y -qq cmake python3-dev python3-pip python3-venv git lcov libgtest-dev pkg-config

  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -e git+https://github.com/antmicro/tuttest#egg=tuttest
    - tuttest README.md warp-pipe-build | bash -oe pipefail -
    
    - tuttest README.md warp-pipe-tests | bash -oe pipefail -
    - tuttest README.md warp-pipe-coverage | bash -oe pipefail -
    - tar czf coverage.tar.gz coverage

  artifacts:
    paths:
      - build/warppipe-tests
      - coverage.tar.gz
    when: always

Build Zephyr Samples:
  stage: build
  tags: ["ace-x86_64"]
  variables:
    SCALENODE_CPU: 8
    SCALENODE_DISK: 10
    SCALENODE_RAM: 8192
    DEBIAN_FRONTEND: noninteractive
    CMAKE_PREFIX_PATH: /opt/toolchains
    GIT_SUBMODULE_STRATEGY: normal
    PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig
  image: "d2s://external/docker/zephyrprojectrtos/ci:v0.26.5"

  before_script:
    - apt update -qq
    - apt-mark hold tzdata # don't update tzdata, as it sometimes fails to update in CI
    - apt upgrade -y -qq
    - apt install -y -qq cmake python3-dev python3-pip python3-venv git lcov libgtest-dev pkg-config

  script:
    - pip3 install -e git+https://github.com/antmicro/tuttest#egg=tuttest
    - tuttest README.md warp-pipe-build,memory-mock-build | bash -oe pipefail -
    - tuttest README.md zephyr-env-prep | bash -oe pipefail -

    # PCIe Scan sample
    - tuttest zephyr-samples/pcie_scan/README.md pcie-scan-build | bash -oe pipefail -
    - tar czf pcie_scan.tar.gz build.pcie_scan

    # PCIe NVMe sample
    - tuttest zephyr-samples/pcie_nvme/README.md pcie-nvme-build | bash -oe pipefail -
    - tar czf pcie_nvme.tar.gz build.pcie_nvme

    # PCIe IVSHMEM sample
    - tuttest zephyr-samples/pcie_ivshmem/README.md pcie-ivshmem-build | bash -oe pipefail -
    - tar czf pcie_ivshmem.tar.gz build.pcie_ivshmem

    # PCIe DMA sample
    - tuttest zephyr-samples/pcie_dma/README.md pcie-dma-build,pcie-dma-run,pcie-dma-teardown | bash -oe pipefail -
    - tar czf pcie_dma.tar.gz build.pcie_dma

    # Run warp-pipe sample
    - tuttest zephyr-samples/pcie_pipe/README.md pcie-qemu-build,pcie-pipe-build,pcie-pipe-run,pcie-pipe-teardown | bash -oe pipefail -
    - tar czf pcie_pipe.tar.gz build.pcie_pipe

  artifacts:
    paths:
      - pcie_*.tar.gz
    when: always

Checkpatch:
  stage: build
  extends: .job_template

  before_script:
    - apt update -qq
    - apt-mark hold tzdata # don't update tzdata, as it sometimes fails to update in CI
    - apt upgrade -y -qq
    - apt install -y -qq wget perl

  script:
    # Download checkpatch.pl script directly from the Linux kernel source tree
    - wget https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/scripts/checkpatch.pl
    - chmod +x checkpatch.pl

    # Use xargs instead of find's -exec due to the status return code limitation in find
    - find . -iname '*.[ch]' -not -path "./build/*" -and -not -path "./tests/*" -and -not -path "./zephyr-samples/drivers/dma/*" | xargs ./checkpatch.pl -f --no-tree
